version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ledger
      POSTGRES_USER: hypo
      POSTGRES_PASSWORD: thesis
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrate
    environment:
      DB_NAME: ledger
      DB_USER: hypo
      DB_PASSWORD: thesis
      DB_HOST: db
      DB_PORT: 5432

  migrate:
    build: .
    command: migrate
    volumes:
      - .:/app
    environment:
      DB_NAME: ledger
      DB_USER: hypo
      DB_PASSWORD: thesis
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:

